name: BannerBoard
main: me.bigteddy98.bannerboard.Main
version: ${project.version}
author: BigTeddy98
commands:
    bannerboard:
        aliases: [bb]
        description: "Main Command of BannerBoard. Use '/bb create' to create a banner."
description: BannerBoard is a lightweight banner board plugin.
softdepend: [PlaceholderAPI]